import * as React from 'react';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { AuthProvider } from "../context/AuthContext";
import { Inter } from "next/font/google";
import theme from '../src/theme/theme';
import './globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "News Letter",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body>
      <AuthProvider>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <ThemeProvider theme={theme}>
            {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
            
            {props.children}
          </ThemeProvider>
        </AppRouterCacheProvider>
        </AuthProvider>
      </body>
    </html>

  )
}




// export default function RootLayout({ children }) {
//   return (
//     <AuthProvider>
//       <html lang="en">
//         <body className={inter.className}>{children}</body>
//       </html>
//     </AuthProvider>
//   );
// }